server:
  port: 0

spring:
  threads:
    virtual:
      enabled: true
  datasource:
    hikari:
      idle-timeout: 30000
      max-lifetime: 180000
      connection-timeout: 30000
      maximum-pool-size: 100
    url: jdbc:mariadb://localhost:3306/gameinfo_user
  application:
    name: user-service
  kafka:
    consumer:
      group-id: userConsumerGroup
    bootstrap-servers: kafka:9093
  rabbitmq:
    host: 127.0.0.1
    port: 5672
  cloud:
    config:
      name: gameinfo,user-service
  config:
    import:
      - "optional:configserver:http://config-server:9088"
  data:
    redis:
      lettuce:
        pool:
          max-active: 150
          max-idle: 50
      host: localhost
      port: 6379
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        default_batch_fetch_size: 1000
        use_id_generator_strategy_three_lo: false
        format_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  zipkin:
    tracing:
      endpoint: ""
    sender:
      type: kafka
    kafka:
      topic: zipkin
      bootstrap-servers: kafka:9093
  endpoints:
    web:
      exposure:
        include:
          - health
          - beans
          - info
          - busrefresh
          - prometheus
          - metrics

logging:
  level:
    root: INFO
    org.springframework.data.redis: ERROR
    io.lettuce.core: ERROR